# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b9483881b462510bbae39f6121adcba40de724ea3632c6eca391f9abf5ca85a93f47021f30407036e1ca620b0f9101b1f80c551fb048248b0da70da5bca25e8

test:
  secret_key_base: 6ad9ec51cd6b9d0604331248b2dfe5d261a800d69dc4c32371f2882c934735f3d06a50fc36b2409e74e2b19920ac64b765a6b5386660df529fcf500a4e40d867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
